import type { VercelRequest, VercelResponse } from '@vercel/node';

type Num = number;
type Candle = { datetime: string; open: Num; high: Num; low: Num; close: Num; volume?: Num };
type AnyRecord = Record<string, unknown>;
const API = 'https://api.twelvedata.com';
const SERVER = { name: 'twelvedata-mcp', version: '2.0.0' };
const candleSchema = { type: 'object', properties: { symbol: { type: 'string' }, interval: { type: 'string' }, start_date: { type: 'string' }, end_date: { type: 'string' }, outputsize: { type: 'integer', minimum: 20, maximum: 5000 }, timezone: { type: 'string' }, exchange: { type: 'string' } }, required: ['symbol', 'interval'] };
const tools = [
 { name: 'get_quote', description: 'Real-time Twelve Data price/quote.', inputSchema: { type: 'object', properties: { symbol: { type: 'string' }, exchange: { type: 'string' }, type: { type: 'string' } }, required: ['symbol'] } },
 { name: 'get_candles', description: 'OHLCV time series from Twelve Data.', inputSchema: candleSchema },
 { name: 'get_indicator', description: 'Calculate a Twelve Data technical indicator.', inputSchema: { type: 'object', properties: { indicator: { type: 'string' }, symbol: { type: 'string' }, interval: { type: 'string' }, time_period: { type: 'integer' }, series_type: { type: 'string' }, outputsize: { type: 'integer' } }, required: ['indicator', 'symbol', 'interval'] } },
 { name: 'get_smc_analysis', description: 'Institutional Smart Money Concepts analysis: swing structure, internal/external BSL and SSL, CHoCH, BOS, unmitigated FVG with 50% CE, and high-probability order blocks. Accepts multi-timeframe candles.', inputSchema: { type: 'object', properties: { symbol: { type: 'string' }, interval: { type: 'string' }, higher_timeframe: { type: 'string' }, candles: { type: 'array' }, higher_timeframe_candles: { type: 'array' }, swing_length: { type: 'integer', minimum: 2, maximum: 20 }, outputsize: { type: 'integer', minimum: 50, maximum: 5000 } }, required: ['symbol', 'interval'] } },
 { name: 'get_smt_divergence', description: 'Compare correlated or inversely correlated assets for SMT divergence.', inputSchema: { type: 'object', properties: { symbol_a: { type: 'string' }, symbol_b: { type: 'string' }, interval: { type: 'string' }, candles_a: { type: 'array' }, candles_b: { type: 'array' }, correlation: { type: 'string', enum: ['correlated', 'inverse'] }, outputsize: { type: 'integer' } }, required: ['symbol_a', 'symbol_b', 'interval'] } },
 { name: 'get_session_liquidity', description: 'Calculate Asia, London, New York and previous-day liquidity levels for killzone sweep detection.', inputSchema: { type: 'object', properties: { symbol: { type: 'string' }, interval: { type: 'string' }, timezone: { type: 'string' }, asia: { type: 'string' }, london: { type: 'string' }, new_york: { type: 'string' }, candles: { type: 'array' }, outputsize: { type: 'integer' } }, required: ['symbol', 'interval'] } },
 { name: 'get_market_filters', description: 'Calculate ADX, ATR and RSI divergence for trade confirmation.', inputSchema: { type: 'object', properties: { symbol: { type: 'string' }, interval: { type: 'string' }, period: { type: 'integer' }, candles: { type: 'array' }, outputsize: { type: 'integer' } }, required: ['symbol', 'interval'] } }
];
const n = (v: unknown): number => { const x = Number(v); if (!Number.isFinite(x)) throw new Error(`Invalid numeric value: ${String(v)}`); return x; };
function normalize(rows: unknown): Candle[] { if (!Array.isArray(rows)) throw new Error('Expected an array of candles'); return rows.map((r: any) => ({ datetime: String(r.datetime ?? r.time ?? ''), open: n(r.open), high: n(r.high), low: n(r.low), close: n(r.close), volume: r.volume == null ? undefined : n(r.volume) })).filter(c => c.datetime).sort((a, b) => a.datetime.localeCompare(b.datetime)); }
async function td(endpoint: string, args: AnyRecord): Promise<any> { const key = process.env.TWELVEDATA_API_KEY; if (!key) throw new Error('TWELVEDATA_API_KEY is not configured'); const p = new URLSearchParams(); for (const [k, v] of Object.entries(args)) if (v !== undefined && v !== null && v !== '') p.set(k, String(v)); p.set('apikey', key); const r = await fetch(`${API}/${endpoint}?${p}`); const d = await r.json(); if (!r.ok || d.status === 'error' || Number(d.code) >= 400) throw new Error(d.message || `Twelve Data request failed (${r.status})`); return d; }
async function candles(args: AnyRecord, override?: unknown): Promise<Candle[]> { if (override) return normalize(override); const d = await td('time_series', args); return normalize(d.values); }
function pivots(c: Candle[], len = 3) { const highs: AnyRecord[] = [], lows: AnyRecord[] = []; for (let i = len; i < c.length - len; i++) { if (c.slice(i-len, i+len+1).every((x, j) => j === len || x.high < c[i].high)) highs.push({ index: i, time: c[i].datetime, price: c[i].high }); if (c.slice(i-len, i+len+1).every((x, j) => j === len || x.low > c[i].low)) lows.push({ index: i, time: c[i].datetime, price: c[i].low }); } return { highs, lows }; }
function structure(c: Candle[], len: number) { const p = pivots(c, len), events: AnyRecord[] = []; let lastH: number | undefined, lastL: number | undefined; for (const x of [...p.highs, ...p.lows].sort((a,b) => Number(a.index)-Number(b.index))) { const isH = p.highs.includes(x); const prior = isH ? lastH : lastL; const broken = isH ? c.slice(Number(x.index)+1).some(z => z.close > Number(x.price)) : c.slice(Number(x.index)+1).some(z => z.close < Number(x.price)); if (broken) events.push({ type: events.length && (isH ? Number(x.price) > (lastH ?? Number(x.price)) : Number(x.price) < (lastL ?? Number(x.price))) ? 'BOS' : 'CHoCH', direction: isH ? 'bullish' : 'bearish', level: x.price, time: x.time, prior }); if (isH) lastH = Number(x.price); else lastL = Number(x.price); } return { pivots: p, events: events.slice(-20) }; }
function liquidity(c: Candle[], p: ReturnType<typeof pivots>) { const hi = p.highs as AnyRecord[], lo = p.lows as AnyRecord[]; const mid = Math.floor(c.length / 2); return { external: { BSL: hi.filter(x => Number(x.index) < mid).slice(-10), SSL: lo.filter(x => Number(x.index) < mid).slice(-10) }, internal: { BSL: hi.filter(x => Number(x.index) >= mid).slice(-10), SSL: lo.filter(x => Number(x.index) >= mid).slice(-10) } }; }
function smc(c: Candle[], len: number) { const p = pivots(c, len), gaps: AnyRecord[] = []; for (let i=2;i<c.length;i++) { if (c[i].low > c[i-2].high) gaps.push({ type:'bullish', from:c[i-2].high, to:c[i].low, CE:(c[i-2].high+c[i].low)/2, time:c[i].datetime, mitigated:c.slice(i+1).some(x=>x.low <= (c[i-2].high+c[i].low)/2) }); if (c[i].high < c[i-2].low) gaps.push({ type:'bearish', from:c[i].high, to:c[i-2].low, CE:(c[i].high+c[i-2].low)/2, time:c[i].datetime, mitigated:c.slice(i+1).some(x=>x.high >= (c[i].high+c[i-2].low)/2) }); } const obs: AnyRecord[] = []; for (const e of structure(c,len).events) { const i = c.findIndex(x=>x.datetime===e.time); const b = c[Math.max(0,i-1)]; if (b) obs.push({ type:e.direction==='bullish'?'bullish':'bearish', high:b.high, low:b.low, time:b.datetime, confirmation:e.type }); } return { swings:p, structure:structure(c,len).events, liquidity:liquidity(c,p), fairValueGaps:gaps.filter(g=>!g.mitigated), orderBlocks:obs.slice(-20) }; }
function atr(c: Candle[], period: number) { const tr=c.map((x,i)=>i?Math.max(x.high-x.low,Math.abs(x.high-c[i-1].close),Math.abs(x.low-c[i-1].close)):x.high-x.low); return tr.slice(-period).reduce((a,b)=>a+b,0)/Math.min(period,tr.length); }
function rsi(c: Candle[], period: number) { let gains=0,loss=0; for(let i=Math.max(1,c.length-period);i<c.length;i++){const d=c[i].close-c[i-1].close;if(d>=0)gains+=d;else loss-=d;} return loss===0?100:100-(100/(1+gains/loss)); }
function filters(c: Candle[], period: number) { const trs=c.slice(1).map((x,i)=>Math.max(x.high-x.low,Math.abs(x.high-c[i].close),Math.abs(x.low-c[i].close))); const plus=c.slice(1).map((x,i)=>x.high-c[i].high>c[i].low-x.low&&x.high-c[i].high>0?x.high-c[i].high:0); const minus=c.slice(1).map((x,i)=>c[i].low-x.low>x.high-c[i].high&&c[i].low-x.low>0?c[i].low-x.low:0); const dx=trs.slice(-period).map((tr,i)=>{const p=plus.slice(-period)[i]/tr*100,m=minus.slice(-period)[i]/tr*100;return Math.abs(p-m)/(p+m||1)*100}); return { ATR:atr(c,period), RSI:rsi(c,period), ADX:dx.reduce((a,b)=>a+b,0)/dx.length, rsiDivergence: rsi(c.slice(0,-Math.max(2,Math.floor(period/2))),period)>rsi(c,period)?'bearish':'bullish' }; }
function sessions(c: Candle[], args: AnyRecord) { const ranges: AnyRecord = { Asia:String(args.asia||'00:00-08:00'), London:String(args.london||'08:00-13:00'), NewYork:String(args.new_york||'13:00-17:00') }; const out: AnyRecord={}; for(const [name,range] of Object.entries(ranges)){const [a,b]=String(range).split('-');const rows=c.filter(x=>{const t=x.datetime.slice(11,16);return t>=a&&t<b});out[name]={high:rows.length?Math.max(...rows.map(x=>x.high)):null,low:rows.length?Math.min(...rows.map(x=>x.low)):null,count:rows.length};} const days: Record<string,Candle[]>={}; for(const x of c){const d=x.datetime.slice(0,10);(days[d]??=[]).push(x)} const ds=Object.keys(days); const prev=days[ds[Math.max(0,ds.length-2)]]||[]; out.previousDay={high:prev.length?Math.max(...prev.map(x=>x.high)):null,low:prev.length?Math.min(...prev.map(x=>x.low)):null}; return out; }
async function run(name: string, a: AnyRecord): Promise<AnyRecord> { if(name==='get_quote') return td('quote',a); if(name==='get_candles') return td('time_series',a); if(name==='get_indicator'){const {indicator,...rest}=a;return td(String(indicator),rest)} if(name==='get_smc_analysis'){const c=await candles(a,a.candles);const result=smc(c,n(a.swing_length||3));return {...result,symbol:a.symbol,interval:a.interval,higherTimeframe:a.higher_timeframe||null};} if(name==='get_smt_divergence'){const [a1,a2]=await Promise.all([candles(a,a.candles_a),candles(a,a.candles_b)]);const m=Math.min(a1.length,a2.length);const x=a1.slice(-m),y=a2.slice(-m),pa=pivots(x,3),pb=pivots(y,3);const hh=(pa.highs.at(-1)?.price??0)>(pa.highs.at(-2)?.price??0)&&(pb.highs.at(-1)?.price??0)<(pb.highs.at(-2)?.price??0);const ll=(pa.lows.at(-1)?.price??0)<(pa.lows.at(-2)?.price??0)&&(pb.lows.at(-1)?.price??0)>(pb.lows.at(-2)?.price??0);return {symbolA:a.symbol_a,symbolB:a.symbol_b,correlation:a.correlation||'correlated',divergence:hh?'bearish SMT':ll?'bullish SMT':'none',higherHighLowerHigh:{a:pa.highs.at(-1),b:pb.highs.at(-1)},lowerLowHigherLow:{a:pa.lows.at(-1),b:pb.lows.at(-1)}};} if(name==='get_session_liquidity') return sessions(await candles(a,a.candles),a); if(name==='get_market_filters') return filters(await candles(a,a.candles),n(a.period||14)); throw new Error(`Unknown tool: ${name}`); }
const rpc=(id:unknown,result:unknown)=>({jsonrpc:'2.0',id,result}); const err=(id:unknown,message:string,code=-32000)=>({jsonrpc:'2.0',id:id??null,error:{code,message}});
export default async function handler(req: VercelRequest,res: VercelResponse){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Content-Type, Accept, MCP-Protocol-Version');res.setHeader('Access-Control-Allow-Methods','GET, POST, OPTIONS');if(req.method==='OPTIONS')return res.status(204).end();if(req.method==='GET'){res.setHeader('Content-Type','text/event-stream');return res.status(200).send('event: endpoint\\ndata: /mcp\\n\\n');}if(req.method!=='POST')return res.status(405).json({error:'Use POST for MCP JSON-RPC.'});try{const body=typeof req.body==='string'?JSON.parse(req.body):req.body;const handle=async(q:AnyRecord)=>{const id=q.id;switch(q.method){case'initialize':return rpc(id,{protocolVersion:'2024-11-05',capabilities:{tools:{listChanged:false}},serverInfo:SERVER});case'ping':return rpc(id,{});case'notifications/initialized':return null;case'tools/list':return rpc(id,{tools});case'tools/call':try{return rpc(id,{content:[{type:'text',text:JSON.stringify(await run(String(q.params?.name),q.params?.arguments||{}),null,2)}]});}catch(e){return rpc(id,{isError:true,content:[{type:'text',text:e instanceof Error?e.message:'Request failed'}]});}default:return err(id,`Method not found: ${q.method}`,-32601);}};const out=await Promise.all((Array.isArray(body)?body:[body]).map(handle));const filtered=out.filter(Boolean);return res.status(filtered.length?200:202).json(Array.isArray(body)?filtered:filtered[0]||{});}catch(e){return res.status(400).json(err(null,e instanceof Error?e.message:'Parse error',-32700));}}
